<a href="https://colab.research.google.com/github/roman-mikhaylov/repo_sinergiya/blob/main/ML_5_6_Mikhaylov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Конспект урока. подготовка данных**

In [79]:
import numpy as np
import pandas as pd

**загрузка данных - здания**

site_id - город

building_id - здание

primary_use - назначение

square_feet - площадь, кв.футы

year_built - год постройки

floor_count - число этажей

In [80]:
building = pd.read_csv("http://video.ittensive.com/machine-learning/ashrae/building_metadata.csv.gz")
building.head()

   site_id  building_id primary_use  square_feet  year_built  floor_count
0        0            0   Education         7432      2008.0          NaN
1        0            1   Education         2720      2004.0          NaN
2        0            2   Education         5376      1991.0          NaN
3        0            3   Education        23685      2002.0          NaN
4        0            4   Education       116607      1975.0          NaN

In [81]:
building.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1449 entries, 0 to 1448
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   site_id      1449 non-null   int64
 1   building_id  1449 non-null   int64
 2   primary_use  1449 non-null   object
 3   square_feet  1449 non-null   int64
 4   year_built   675 non-null    float64
 5   floor_count  355 non-null    float64
dtypes: float64(2), int64(3), object(1)
memory usage: 68.0+ KB

**Загрузка данных: погода**

air_temperature - температура воздуха, С

cloud_coverage  - облачность, %

dew_temperature - точка росы(влажность), С

precip_depth_1_hr - кол-во осадков, мм/час

sea_level_pressure - давление, бар

wind_direction - направление ветра, градусы

wind_speed - скорость ветра, м/с

In [82]:
weather = pd.read_csv("http://video.ittensive.com/machine-learning/ashrae/weather_train.csv.gz")
weather.head()

,site_id,timestamp,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,0,2016-01-01 00:00:00,25.0,6.0,20.0,NaN,1019.7,0.0,0.0
1,0,2016-01-01 01:00:00,24.4,NaN,21.1,-1.0,1020.2,70.0,1.5
2,0,2016-01-01 02:00:00,22.8,2.0,21.1,0.0,1020.2,0.0,0.0
3,0,2016-01-01 03:00:00,21.1,2.0,20.6,0.0,1020.1,0.0,0.0
4,0,2016-01-01 04:00:00,20.0,2.0,20.0,-1.0,1020.0,250.0,2.6

**Загрузка данных: потребление здания 0**

meter_reading - значение показателя ТОЕ (эквавалент тонны нефти)

In [83]:
energy_0 = pd.read_csv("http://video.ittensive.com/machine-learning/ashrae/train.0.0.csv.gz")
energy_0

      building_id  meter            timestamp  meter_reading
0               0      0  2016-01-01 00:00:00          0.000
1               0      0  2016-01-01 01:00:00          0.000
2               0      0  2016-01-01 02:00:00          0.000
3               0      0  2016-01-01 03:00:00          0.000
4               0      0  2016-01-01 04:00:00          0.000
...           ...    ...                  ...            ...
8779            0      0  2016-12-31 19:00:00        232.071
8780            0      0  2016-12-31 20:00:00        189.069
8781            0      0  2016-12-31 21:00:00        169.958
8782            0      0  2016-12-31 22:00:00        169.958
8783            0      0  2016-12-31 23:00:00        175.418

[8784 rows x 4 columns]

**Обьединение потребления энергии и информации о здании**

по building_id

In [84]:
# аналог короткий)
energy_0 = pd.merge(energy_0,building,on='building_id')
energy_0

,building_id,meter,timestamp,meter_reading,site_id,primary_use,square_feet,year_built,floor_count
0,0,0,2016-01-01 00:00:00,0.000,0,Education,7432,2008.0,NaN
1,0,0,2016-01-01 01:00:00,0.000,0,Education,7432,2008.0,NaN
2,0,0,2016-01-01 02:00:00,0.000,0,Education,7432,2008.0,NaN
3,0,0,2016-01-01 03:00:00,0.000,0,Education,7432,2008.0,NaN
4,0,0,2016-01-01 04:00:00,0.000,0,Education,7432,2008.0,NaN
...,...,...,...,...,...,...,...,...,...
8779,0,0,2016-12-31 19:00:00,232.071,0,Education,7432,2008.0,NaN
8780,0,0,2016-12-31 20:00:00,189.069,0,Education,7432,2008.0,NaN
8781,0,0,2016-12-31 21:00:00,169.958,0,Education,7432,2008.0,NaN
8782,0,0,2016-12-31 22:00:00,169.958,0,Education,7432,2008.0,NaN
8783,0,0,2016-12-31 23:00:00,175.418,0,Education,7432,2008.0,NaN

In [85]:
# подлиннее
energy_0_merge1 = pd.merge(left=energy_0, right=building, how = 'left', left_on = 'building_id', right_on =	'building_id')
energy_0_merge1

,building_id,meter,timestamp,meter_reading,site_id_x,primary_use_x,square_feet_x,year_built_x,floor_count_x,site_id_y,primary_use_y,square_feet_y,year_built_y,floor_count_y
0,0,0,2016-01-01 00:00:00,0.000,0,Education,7432,2008.0,NaN,0,Education,7432,2008.0,NaN
1,0,0,2016-01-01 01:00:00,0.000,0,Education,7432,2008.0,NaN,0,Education,7432,2008.0,NaN
2,0,0,2016-01-01 02:00:00,0.000,0,Education,7432,2008.0,NaN,0,Education,7432,2008.0,NaN
3,0,0,2016-01-01 03:00:00,0.000,0,Education,7432,2008.0,NaN,0,Education,7432,2008.0,NaN
4,0,0,2016-01-01 04:00:00,0.000,0,Education,7432,2008.0,NaN,0,Education,7432,2008.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,0,0,2016-12-31 19:00:00,232.071,0,Education,7432,2008.0,NaN,0,Education,7432,2008.0,NaN
8780,0,0,2016-12-31 20:00:00,189.069,0,Education,7432,2008.0,NaN,0,Education,7432,2008.0,NaN
8781,0,0,2016-12-31 21:00:00,169.958,0,Education,7432,2008.0,NaN,0,Education,7432,2008.0,NaN
8782,0,0,2016-12-31 22:00:00,169.958,0,Education,7432,2008.0,NaN,0,Education,7432,2008.0,NaN
8783,0,0,2016-12-31 23:00:00,175.418,0,Education,7432,2008.0,NaN,0,Education,7432,2008.0,NaN

**Обьединение потребления энергии и погоды**

выставим индексы  для обьединения timstamp, sity_id

In [86]:
energy_0.set_index(['timestamp', 'site_id'], inplace=True)
weather.set_index(['timestamp', 'site_id'], inplace=True)

проводим обьедиение и сбросим индексы

In [87]:
energy_0 = pd.merge(left=energy_0, right=weather, how = 'left', left_index = True, right_index =	True)
energy_0.reset_index(inplace=True)
energy_0.head()

,timestamp,site_id,building_id,meter,meter_reading,primary_use,square_feet,year_built,floor_count,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed
0,2016-01-01 00:00:00,0,0,0,0.0,Education,7432,2008.0,NaN,25.0,6.0,20.0,NaN,1019.7,0.0,0.0
1,2016-01-01 01:00:00,0,0,0,0.0,Education,7432,2008.0,NaN,24.4,NaN,21.1,-1.0,1020.2,70.0,1.5
2,2016-01-01 02:00:00,0,0,0,0.0,Education,7432,2008.0,NaN,22.8,2.0,21.1,0.0,1020.2,0.0,0.0
3,2016-01-01 03:00:00,0,0,0,0.0,Education,7432,2008.0,NaN,21.1,2.0,20.6,0.0,1020.1,0.0,0.0
4,2016-01-01 04:00:00,0,0,0,0.0,Education,7432,2008.0,NaN,20.0,2.0,20.0,-1.0,1020.0,250.0,2.6

**Задание**

1.используем линейную интерполяцию для температуры воздуха, облачности и точки росы

**Заполнение пропущенных данных**

air_temperature Nan -> линейная интерполяция

cloud_coverage	Nan -> линейная интерполяция

dew_temperature Nan -> линейная интерполяция

In [88]:
energy_0['cloud_coverage'].interpolate()

0       6.0
1       4.0
2       2.0
3       2.0
4       2.0
       ...
8779    4.0
8780    4.0
8781    4.0
8782    4.0
8783    4.0
Name: cloud_coverage, Length: 8784, dtype: float64

In [89]:
energy_0['air_temperature'].interpolate()

0       25.0
1       24.4
2       22.8
3       21.1
4       20.0
        ...
8779    22.8
8780    23.3
8781    23.3
8782    22.8
8783    20.6
Name: air_temperature, Length: 8784, dtype: float64

In [90]:
energy_0['dew_temperature'].interpolate()

0       20.0
1       21.1
2       21.1
3       20.6
4       20.0
        ...
8779    10.0
8780     8.9
8781    10.0
8782    10.0
8783    10.0
Name: dew_temperature, Length: 8784, dtype: float64

**2. вычислите первую производную для температуры воздуха и записать ее в столбец air_temperature1**

In [91]:
# Вычисляем производную для столбца
from sympy import *
#energy_0['air_temperature1'] = energy_0['air_temperature'].apply(lambda x: np.diff(x)/np.diff(x.index))

energy_0['air_temperature1'] = energy_0['air_temperature'].diff() # первая будет Nan, потом удалим строку
energy_0

,timestamp,site_id,building_id,meter,meter_reading,primary_use,square_feet,year_built,floor_count,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed,air_temperature1
0,2016-01-01 00:00:00,0,0,0,0.000,Education,7432,2008.0,NaN,25.0,6.0,20.0,NaN,1019.7,0.0,0.0,NaN
1,2016-01-01 01:00:00,0,0,0,0.000,Education,7432,2008.0,NaN,24.4,NaN,21.1,-1.0,1020.2,70.0,1.5,-0.6
2,2016-01-01 02:00:00,0,0,0,0.000,Education,7432,2008.0,NaN,22.8,2.0,21.1,0.0,1020.2,0.0,0.0,-1.6
3,2016-01-01 03:00:00,0,0,0,0.000,Education,7432,2008.0,NaN,21.1,2.0,20.6,0.0,1020.1,0.0,0.0,-1.7
4,2016-01-01 04:00:00,0,0,0,0.000,Education,7432,2008.0,NaN,20.0,2.0,20.0,-1.0,1020.0,250.0,2.6,-1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,2016-12-31 19:00:00,0,0,0,232.071,Education,7432,2008.0,NaN,22.8,NaN,10.0,0.0,1021.7,140.0,5.7,1.1
8780,2016-12-31 20:00:00,0,0,0,189.069,Education,7432,2008.0,NaN,23.3,NaN,8.9,0.0,1021.0,170.0,4.1,0.5
8781,2016-12-31 21:00:00,0,0,0,169.958,Education,7432,2008.0,NaN,23.3,NaN,10.0,0.0,1021.1,150.0,4.1,0.0
8782,2016-12-31 22:00:00,0,0,0,169.958,Education,7432,2008.0,NaN,22.8,NaN,10.0,0.0,1021.1,160.0,3.1,-0.5
8783,2016-12-31 23:00:00,0,0,0,175.418,Education,7432,2008.0,NaN,20.6,NaN,10.0,0.0,1021.1,0.0,0.0,-2.2

**3 вычислите синус и косинус от угла направления ветра, записать их в столбцы wind_direction_cos, wind_direction_sin**

In [92]:
energy_0['wind_direction_cos'] = np.cos(energy_0['wind_direction'])
energy_0['wind_direction_sin'] = np.sin(energy_0['wind_direction'])
energy_0

,timestamp,site_id,building_id,meter,meter_reading,primary_use,square_feet,year_built,floor_count,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_direction,wind_speed,air_temperature1,wind_direction_cos,wind_direction_sin
0,2016-01-01 00:00:00,0,0,0,0.000,Education,7432,2008.0,NaN,25.0,6.0,20.0,NaN,1019.7,0.0,0.0,NaN,1.000000,0.000000
1,2016-01-01 01:00:00,0,0,0,0.000,Education,7432,2008.0,NaN,24.4,NaN,21.1,-1.0,1020.2,70.0,1.5,-0.6,0.633319,0.773891
2,2016-01-01 02:00:00,0,0,0,0.000,Education,7432,2008.0,NaN,22.8,2.0,21.1,0.0,1020.2,0.0,0.0,-1.6,1.000000,0.000000
3,2016-01-01 03:00:00,0,0,0,0.000,Education,7432,2008.0,NaN,21.1,2.0,20.6,0.0,1020.1,0.0,0.0,-1.7,1.000000,0.000000
4,2016-01-01 04:00:00,0,0,0,0.000,Education,7432,2008.0,NaN,20.0,2.0,20.0,-1.0,1020.0,250.0,2.6,-1.1,0.240988,-0.970528
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,2016-12-31 19:00:00,0,0,0,232.071,Education,7432,2008.0,NaN,22.8,NaN,10.0,0.0,1021.7,140.0,5.7,1.1,-0.197814,0.980240
8780,2016-12-31 20:00:00,0,0,0,189.069,Education,7432,2008.0,NaN,23.3,NaN,8.9,0.0,1021.0,170.0,4.1,0.5,0.937995,0.346649
8781,2016-12-31 21:00:00,0,0,0,169.958,Education,7432,2008.0,NaN,23.3,NaN,10.0,0.0,1021.1,150.0,4.1,0.0,0.699251,-0.714876
8782,2016-12-31 22:00:00,0,0,0,169.958,Education,7432,2008.0,NaN,22.8,NaN,10.0,0.0,1021.1,160.0,3.1,-0.5,-0.975629,0.219425
8783,2016-12-31 23:00:00,0,0,0,175.418,Education,7432,2008.0,NaN,20.6,NaN,10.0,0.0,1021.1,0.0,0.0,-2.2,1.000000,0.000000

**4.Удалить столбцы site_id building_id meter	primary_use square_feet year_built floor_count wind_direction**

In [93]:
energy_0.drop(['site_id', 'building_id', 'meter', 'primary_use', 'square_feet', 'year_built', 'floor_count', 'wind_direction'], axis=1, inplace=True)
energy_0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   timestamp           8784 non-null   object
 1   meter_reading       8784 non-null   float64
 2   air_temperature     8781 non-null   float64
 3   cloud_coverage      4954 non-null   float64
 4   dew_temperature     8781 non-null   float64
 5   precip_depth_1_hr   8783 non-null   float64
 6   sea_level_pressure  8699 non-null   float64
 7   wind_speed          8784 non-null   float64
 8   air_temperature1    8779 non-null   float64
 9   wind_direction_cos  8534 non-null   float64
 10  wind_direction_sin  8534 non-null   float64
dtypes: float64(10), object(1)
memory usage: 755.0+ KB

**5. Удалите из данных строки с metr_reading = 0**

In [94]:
#df = df[df['col']] != 'target'

index_names = energy_0[energy_0['meter_reading'] == 0].index
energy_0.drop(index_names, inplace = True)
energy_0

,timestamp,meter_reading,air_temperature,cloud_coverage,dew_temperature,precip_depth_1_hr,sea_level_pressure,wind_speed,air_temperature1,wind_direction_cos,wind_direction_sin
704,2016-01-30 08:00:00,43.6839,8.3,NaN,6.1,0.0,1019.0,2.1,-2.3,0.996085,0.088399
725,2016-01-31 05:00:00,37.5408,12.8,NaN,10.0,0.0,1021.9,0.0,-1.1,1.000000,0.000000
737,2016-01-31 17:00:00,52.5571,20.6,NaN,11.7,0.0,1020.9,1.5,1.7,-0.999021,-0.044243
2366,2016-04-08 14:00:00,59.3827,21.7,2.0,14.4,0.0,1015.1,3.1,2.8,0.240988,-0.970528
2923,2016-05-01 19:00:00,448.0000,31.1,NaN,17.2,0.0,1016.1,4.1,1.1,0.862319,-0.506366
...,...,...,...,...,...,...,...,...,...,...,...
8779,2016-12-31 19:00:00,232.0710,22.8,NaN,10.0,0.0,1021.7,5.7,1.1,-0.197814,0.980240
8780,2016-12-31 20:00:00,189.0690,23.3,NaN,8.9,0.0,1021.0,4.1,0.5,0.937995,0.346649
8781,2016-12-31 21:00:00,169.9580,23.3,NaN,10.0,0.0,1021.1,4.1,0.0,0.699251,-0.714876
8782,2016-12-31 22:00:00,169.9580,22.8,NaN,10.0,0.0,1021.1,3.1,-0.5,-0.975629,0.219425
8783,2016-12-31 23:00:00,175.4180,20.6,NaN,10.0,0.0,1021.1,0.0,-2.2,1.000000,0.000000

In [95]:
energy_0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5411 entries, 704 to 8783
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   timestamp           5411 non-null   object
 1   meter_reading       5411 non-null   float64
 2   air_temperature     5411 non-null   float64
 3   cloud_coverage      3150 non-null   float64
 4   dew_temperature     5411 non-null   float64
 5   precip_depth_1_hr   5411 non-null   float64
 6   sea_level_pressure  5383 non-null   float64
 7   wind_speed          5411 non-null   float64
 8   air_temperature1    5411 non-null   float64
 9   wind_direction_cos  5236 non-null   float64
 10  wind_direction_sin  5236 non-null   float64
dtypes: float64(10), object(1)
memory usage: 507.3+ KB

запишем результат в csv

In [96]:
energy_0.to_csv('energy_0.csv', index=False)